#print("Hello World!\nHello world!\nHello world!")
#print("Hello" + " " + "Seda")
#print("Hello s" + input("What is your name"))

print("Welcome to the Band Name Generator.")
print("What's name of the city you grew up in?")
a = input()
print("What's your pet's name?")
b = input()
print("Your band name could be", a +" "+ b )